### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by laurijamsa** [NordicSemiconductor/Android-nRF-Beacon-for-Eddystone#2]
When I try to register an UID beacon, I get

**Error 403**
_Error message: Unknown error_
_Error status: Unable to register beacon_

I'm running `https://github.com/NordicSemiconductor/nrf5-sdk-for-eddystone/blob/master/hex/nrf5_sdk_for_eddystone_v0.6.hex` and using the latest app version on Galaxy S7 Edge.

Another thing: AFAIK after the slot has been enabled, it cannot be disabled. Only replaced. So maybe you could add one more frame type called "EMPTY"? Or just a trash bin icon. User might also need some help documentation that can be read directly from the app. At the moment it's pretty hard to use if the user is not really familiar with the Eddystone specs. Or at least a link pointing to documentation.

**Comment by roshanrajaratnam** [comment]
@laurijamsa I am looking at the 403 issue as it is something to do with granting permissions to the proximity api. Were you prompted asking to grant authorization to the proximity API? I bet it must have on the older version. I will debug this and get back to you. 
 
Regarding the second issue, you can clear the existing or a newly created slot by pressing the trash bin icon on the toolbar. This will clear the slot and the UI will show up as an Empty slot. I will look in to some help documentation as well.

**Comment by laurijamsa** [comment]
Yeah the app asked my permission and I granted it.

Hah, I didn't notice that trash bin icon 👍  It's working great.

**Comment by roshanrajaratnam** [comment]
Ok so did it not ask you permission before for the beacon platform? did you do anything different than last time?

**Comment by laurijamsa** [comment]
This was a first time I tried to register a beacon. If I recall correctly, the app asked something about the permissions after updating it yesterday.

**Comment by roshanrajaratnam** [comment]
Ok, so I suppose we could close the issue. Usually this happens only if you haven't granted authorization to the proximity API and the app will ensure if the permission is granted.
