### ISSUE TITLE
App stops working when editing nRF52 Devkit

### ISSUE THREAD

**Issue by brunoandretto** [NordicSemiconductor/Android-nRF-Beacon-for-Eddystone#3]
After following the "How to Guide" of the project readme and connecting to the Eddystone Beacon Devkit, I tried editing one of its slots, but as soon as I touched the edit button, the app crashed. At this point, I was using a Moto G.
Using another Android (this time a Samsung Galaxy S5) and following the same procedure, after pressing the edit button the app did not crash. So I selected EID and a value of K between 10 and 15, but submitting generated an error message, suggesting to wait some time and try again, even though, it never worked.

**Comment by roshanrajaratnam** [comment]
hi @brunoandretto can you elaborate more on the crash scenario as I cannot see this on my end.
Did you grant permissions to the proximity api when requested when you switched to the update tab? This is the reason why you were not able to register the beacon!

**Comment by brunoandretto** [comment]
Hi, Roshan! @roshanrajaratnam 
Thank you very much for the fast reply. That was exactly the case: I had changed credentials for my phone's google account and therefore had no permission granted in the app anymore.
I have another Issue now. I can edit the Devkit (and did so) adding slots with EID frame type. But i can't really find the beacon through Beacon Tools app, and neither from beacon-platform API (https://github.com/google/beacon-platform/tree/master/samples/android). I made sure to create OAuth 2.0 client ID and API Key but it still couldn't find the beacon.
Should the app automaticaly register the beacon to a project associated with my google account?
Thank you again.

**Comment by roshanrajaratnam** [comment]
Well the application will not automatically register the beacon. You will have to register the beacon using the overflow menu. Once you register it you should be able to see it from the Beacons tab on the nRF Beacon for Eddystone App. It will only register to the project associated with the API Key and your google account. Let me know how it goes and also any issues not related to this project  must be posted on https://devzone.nordicsemi.com/questions/
