### ISSUE TITLE
Gradle build finished with 4 errors

### ISSUE THREAD

**Issue by EdgarDiez** [NordicSemiconductor/Android-nRF-Beacon-for-Eddystone#4]
Hi, 

I'm trying to do some tests with Android Studio, but the app returns these 4 errors:

- Error:(48, 17) No resource found that matches the given name (at 'text' with value '@string/scanning_info').

- Error:(30, 24) No resource found that matches the given name (at 'title' with value '@string/action_about').

- Error:(30, 24) No resource found that matches the given name (at 'title' with value '@string/action_remove').

- Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/Mitoman/Library/Android/sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1

![captura de pantalla 2016-05-23 a las 11 45 27](https://cloud.githubusercontent.com/assets/17253609/15467347/4a67c2c2-20de-11e6-9767-f10539cc8631.png)

![captura de pantalla 2016-05-23 a las 11 45 33](https://cloud.githubusercontent.com/assets/17253609/15467354/54737892-20de-11e6-8924-63d5d884d3f5.png)

![captura de pantalla 2016-05-23 a las 11 45 36](https://cloud.githubusercontent.com/assets/17253609/15467360/5d2b3448-20de-11e6-8c53-d9289a9331bf.png)

How I can fix it? Thanks!

**Comment by roshanrajaratnam** [comment]
Hi Sorry, this was my bad..some of the refractoring wasn't reflected properly in the commit. If you clone the repository again and build it will be fine. I have now made the changes and committed! Let me know how it goes and I can then close this issue. Thanks

**Comment by EdgarDiez** [comment]
It works great! Thank you so much!

**Comment by roshanrajaratnam** [comment]
Good to hear!
