### ISSUE TITLE
Problem to sign in with my account google to list google projects

### ISSUE THREAD

**Issue by UlyssesGomes** [NordicSemiconductor/Android-nRF-Beacon-for-Eddystone#7]
Hi, 

I am not able to log in with my google account. No error is triggered when I try to log in and the following message is shown in the application "Please sign in with your google account to register / select projects for beacon registration.". But the account I used has the project with the credentials set up and added the API's to the beacon proximity, nearby messages and URL shortener. I put the api key into the Utils class and into android.manifest too. Following is the screen shot of the error and the message displayed in the application.

![screenshot_2017-06-05-14-29-31_br edu ufcg virtus honeywell eddystone](https://user-images.githubusercontent.com/15035210/26894377-9cc59670-4b94-11e7-9c5b-2c0bd0070228.png)

Note: permissions for the BeaconEditor, AttachmentEditor, and AttachmentPublisher were also given.

**Comment by roshanrajaratnam** [comment]
Hi have you been able to sign in on the app with the Google account set up on your phone? Did you get to select the Google account and grant permissions?

**Comment by UlyssesGomes** [comment]
I used the email from the phone and allowed all the permissions that the application requested. Is it necessary to allow some other permission that is not explicit in the repository description?

**Comment by roshanrajaratnam** [comment]
Right. Have you also added the client secret as mentioned in the description. There is nothing specific that is not mentioned in the repo

**Comment by UlyssesGomes** [comment]
What is the "client secret"?

**Comment by laccf** [comment]
@roshanrajaratnam , it's weard, beacause google says that client_secret is no longer necessary:
https://developers.google.com/drive/android/auth

so, how could we fix this using client_secret? could you help us?

**Comment by roshanrajaratnam** [comment]
I think you're looking at the wrong documentation as to what's pointed out in the repository. https://developers.google.com/identity/sign-in/android/start-integrating

**Comment by laccf** [comment]
@roshanrajaratnam , you right, i'm sorry. following this doc, I got another issue. The app cannot show my projects:

![photo_2017-06-08_10-09-16](https://user-images.githubusercontent.com/12553502/26930164-ca36f1d2-4c32-11e7-9948-ea7d2f58d8a8.jpg)

I've tried too many possibilities to set the values of this variables:

![untitled](https://user-images.githubusercontent.com/12553502/26930190-f0a1d490-4c32-11e7-813d-79158df4f48c.png)

At first, when the app is running, the code does not set the correct values (it always sets empsty value):

![image](https://user-images.githubusercontent.com/12553502/26930722-add94600-4c34-11e7-8651-1fc868e981e9.png)

But when I force the value, like this:
![image](https://user-images.githubusercontent.com/12553502/26930766-d6ba23a0-4c34-11e7-9559-6ec802febf1b.png)

I always got the error, that means I'm using the wrong token:
Response{protocol=h2, code=401, message=, url=https://cloudresourcemanager.googleapis.com/v1beta1/projects}

Do you know where do I get the Token that I should use here?

**Comment by roshanrajaratnam** [comment]
No problem, happy to help.

With your second issue, the token is something you receive when you Sign in with your Google account. So if you look at the GoogleSignInDialogFragment you can see the token is saved in the shared preferences. This token is used through out the app to make the calls to project selection etc, so I suggest having a look there if you receive your token in the first place.

**Comment by laccf** [comment]
Thanks again, @roshanrajaratnam . The code never runs the methods saveAccessToken and saveNewAccessToken from GoogleSignInDialogFragment . I tried to debug this before, and the deal is that it never runs. So, if it never runs, probably there is a issue that happens before that. I'll look up that.

**Comment by laccf** [comment]
@roshanrajaratnam , what about this `.add("client_secret", "ADD_YOUR_CLIENT_SECRET")` that are in RefreshAccessTokenTask.java and RequestAccessTokenTask.java, do you know something about that?

**Comment by roshanrajaratnam** [comment]
This is the client secret I was referring to before. I think it's my bad that it's not mentioned in here in the documentation properly. This is th client secret you get when you create your oauth 2.0 client ID in your Google console project.

**Comment by laccf** [comment]
@roshanrajaratnam , thank you so much. we made it. I got the client secret from the client that i've been using the Id and it works properly.

**Comment by roshanrajaratnam** [comment]
That's great to here. I will close the issue if everything is working for you.

**Comment by UlyssesGomes** [comment]
It is everything ok now. Thank you for you help @roshanrajaratnam. :)
